### ISSUE TITLE
Rework challenge runner

### ISSUE THREAD

**Issue by mdp** [openzim/freecodecamp#2]
We currently have the runner working, but it fails to take into account a couple of edge cases. We should rework it to suppor the following:

- Return back which hints passed and which failed
- Allow for syntax errors to still pass - see: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions
    -  This will likely required us to eval the code for each hint 2x, once in the context of the eval statement, and once outside with the code contents available for regex checking.

**Comment by mdp** [comment]
I initially avoided using the FCC evaluator just because this initial pass was so simple, but it would be nice to support more challenge types. Keeping this open while we wait for feedback on the project.

**Comment by benoit74** [comment]
We already now which hints have passed and which failed in prod ZIM.
Syntax error are OK as well. 
There is still a problem on local-scope-and-function case, but I will open a distinct issue.
