### ISSUE TITLE
Enhance explanations / checks around what is supported by the scrapper

### ISSUE THREAD

**Issue by benoit74** [openzim/freecodecamp#21]
Currently, the README states that:
```
Currently this scraper only supports Javascript challenges.
```

However, it is a bit unclear what Javascript challenges are exactly. 

Is it only courses under the `javascript-algorithms-and-data-structures` superBlock?

If yes, is there any reason not to include `es6` in the sample commands?

And finally, regarding these sample commands, what is the logic around course order in the CSV? Is it based only on personal taste?

@rgaudin @mdp your help is more than welcomed 😃

**Comment by rgaudin** [comment]
It's based on the kind of course ; those JS course have this tester that has been implemented while other languages use videos for instance. I think you'll have to check to `es6` and it's possible there are some compatible courses here and there.

As for the list in the README (CSV???) I believe that's the order from the folder listing. Not sure though

**Comment by benoit74** [comment]
How do I find what is the kind of a course? is it linked to the challengeType property?

**Comment by benoit74** [comment]
The CSV = the Comma Separated Value (i.e. the --course parameter which is comma separated)
